os: windows
language: bash
branches: master

before_install: 
  # Detect if any resource files changed
  - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE '(\.rc$)'
      then
        echo "No resource files changed. Aborting!"
        exit
      fi

# Install Resource Hacker
install: choco install reshack

before_script: 
  # Write script file for Resource Hacker
  - cd _compile
  - echo \[FILENAMES\] >> tmp.txt
  - echo Exe=    Domino.exe >> tmp.txt
  - echo SaveAs= Domino.exe >> tmp.txt
  - echo Log=  CON >> tmp.txt
  - echo \[COMMANDS\] >> tmp.txt
  - echo -delete  MENU,, >> tmp.txt
  - echo -delete  DIALOG,, >> tmp.txt
  - echo -delete  STRINGTABLE,, >> tmp.txt
  - echo -add   Menu.res, MENU,, >> tmp.txt
  - echo -add   Dialog.res, DIALOG,, >> tmp.txt
  - echo -add   StringTable.res, STRINGTABLE,, >> tmp.txt

script:
  # Merge all .rc to each .rc groups
  - cat ../Dialog/* > Dialog.rc
  - cat ../Menu/* > Menu.rc
  - cat ../StringTable/* > StringTable.rc
  # Compiling .rc to .res
  - '"C:\Program Files (x86)\Resource Hacker\ResourceHacker.exe" -open Dialog.rc -save Dialog.res -action compile -log CON'
  - '"C:\Program Files (x86)\Resource Hacker\ResourceHacker.exe" -open Menu.rc -save Menu.res -action compile -log CON'
  - '"C:\Program Files (x86)\Resource Hacker\ResourceHacker.exe" -open StringTable.rc -save StringTable.res -action compile -log CON'
  # Replacing resource texts with the new .res
  - '"C:\Program Files (x86)\Resource Hacker\ResourceHacker.exe" -script tmp.txt'
  - touch Domino.exe
  # Remove temp files
  - rm -rf *.rc
  - rm -rf *.res
  - rm -rf tmp.*

before_deploy:
  # Set build date
  - export BUILD_DATE="$(git log -1 --format="%at" | xargs -I{} date -d @{} +%Y%m%d%H%M%S)"
  - export BUILD_DATE_TIDY="$(git log -1 --format="%at" | xargs -I{} date -d @{} +'%Y/%m/%d %H:%M:%S')"  
  # Zipping for publishing
  - 7z a ../Domino143_Translated_v$TRAVIS_BUILD_NUMBER-nightly.$BUILD_DATE.zip *
  - mv -v Domino.exe ../Domino_Translated_v$TRAVIS_BUILD_NUMBER-nightly.$BUILD_DATE.exe
  # Tagging commit
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - cd ..

# Deploy the nightly releases!
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - Domino143_Translated_v$TRAVIS_BUILD_NUMBER-nightly.$BUILD_DATE.zip
    - Domino_Translated_v$TRAVIS_BUILD_NUMBER-nightly.$BUILD_DATE.exe
  skip_cleanup: true
  tag_name: 1.43-en.$TRAVIS_BUILD_NUMBER-nightly.$BUILD_DATE
  name: Build $TRAVIS_BUILD_NUMBER-nightly.$BUILD_DATE – $BUILD_DATE_TIDY
  body: $TRAVIS_COMMIT
  prerelease: true