on: workflow_dispatch

name: Force Nightly Deployment

jobs:
  deploy:
    name: Deployment
    runs-on: windows-latest
    if: github.actor == github.event.repository.owner.login
    defaults:
      run:
        shell: bash
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install required packages
        run: choco install reshack python3

      - name: Build
        id: build
        run: |
          cd _script
          bash build-1.43-nightly.sh
          bash build-1.44-nightly.sh

      - name: Write release body
        run: |
          echo "\
          " >> release.txt
          if [ ! -s _deploy/release-notes.md ]; then
            echo "*No release notes supplied.*" >> release.txt
          else
            cat _deploy/release-notes.md >> release.txt
          fi
          echo "\

          " >> release.txt
          for commit in $(git log --since today.midnight --pretty=%H -- '*.rc'); do
            echo - $commit $(git show --format="%s" $commit | head -1) \($(git show --format="%an" $commit | head -1)\) >> release.txt
          done
          echo "\

          ----

          *Built on ${{steps.build.outputs.BUILD_DATE_FULL}}.*
          *Commits listed are the ones that translated some files.*" >> release.txt
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: en.${{steps.build.outputs.VERSION_NUM}}-nightly.${{steps.build.outputs.BUILD_DATE}}
          name: Build ${{steps.build.outputs.VERSION_NUM}} (Nightly ${{steps.build.outputs.BUILD_DATE_TIDY}})
          prerelease: true
          files: |
            _script/dist/Domino143_Translated.zip
            _script/dist/Domino143_Translated.exe
            _script/dist/Domino144_Translated.zip
            _script/dist/Domino144_Translated.exe
          body_path: release.txt
          draft: true