name: Push/PR Check
on:
  push:
    branches:
      - master
    paths:
      - "**/Dialog/*"
      - "**/Manual/*"
      - "**/Menu/*"
      - "**/Module/*"
      - "**/Other/*"
      - "**/StringTable/*"
      - "**/System/*"
      - "**/VersionInfo/*"
      - "**/240/*"
      - ".github/workflows/*"
      - "_script/*"
  pull_request:
    branches:
      - master
    paths:
      - "**/Dialog/*"
      - "**/Manual/*"
      - "**/Menu/*"
      - "**/Module/*"
      - "**/Other/*"
      - "**/StringTable/*"
      - "**/System/*"
      - "**/VersionInfo/*"
      - "**/240/*"
      - ".github/workflows/*"
      - "_script/*"

jobs:
  deploy:
    name: Deployment
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    
      # - name: Calculate depth
      #   id: depth
      #   run: |
      #     echo DEPTH=$(($(echo '${{toJSON(github.event.commits)}}' | jq '. | length') + 1))
      #     echo ::set-output name=DEPTH::$(($(echo '${{toJSON(github.event.commits)}}' | jq '. | length') + 1))

      - name: Checkout code
        uses: actions/checkout@v4
      #   with:
      #     fetch-depth: ${{steps.depth.outputs.DEPTH}}
      # - name: Check changes
      #   run: |
      #     git diff --name-only $(echo ${{github.event.compare}} | grep -oE '([a-z0-9]+\.\.\.[a-z0-9]+)')
      #     if ! git diff --name-only $(echo ${{github.event.compare}} | grep -oE '([a-z0-9]+\.\.\.[a-z0-9]+)') | grep -E '^((Dialog)|(Manual)|(Menu)|(Module)|(Other)|(StringTable)|(System)|(VersionInfo)|(240)\/)'; then
      #       echo "No files translated. Stopping!"
      #       exit 1
      #     else
      #       echo "Some files translated. Continuing."
      #     fi

      - name: Install required packages
        run: choco install reshack

      - name: Build
        id: build
        run: |
          cd _script
          bash workflow/build-all-artifact.sh

      - name: Upload artifact 1
        uses: actions/upload-artifact@v3
        with:
          name: Domino143_Translated_v${{steps.build.outputs.VERSION_NUM}}-artifact.${{steps.build.outputs.BUILD_DATE}}.zip
          path: _script/dist/Domino143_Translated.zip

      - name: Upload artifact 2
        uses: actions/upload-artifact@v3
        with:
          name: Domino143_Translated_v${{steps.build.outputs.VERSION_NUM}}-artifact.${{steps.build.outputs.BUILD_DATE}}.exe
          path: _script/dist/Domino143_Translated.exe

      - name: Upload artifact 3
        uses: actions/upload-artifact@v3
        with:
          name: Domino144_Translated_v${{steps.build.outputs.VERSION_NUM}}-artifact.${{steps.build.outputs.BUILD_DATE}}.zip
          path: _script/dist/Domino144_Translated.zip

      - name: Upload artifact 4
        uses: actions/upload-artifact@v3
        with:
          name: Domino144_Translated_v${{steps.build.outputs.VERSION_NUM}}-artifact.${{steps.build.outputs.BUILD_DATE}}.exe
          path: _script/dist/Domino144_Translated.exe