on: push

name: Push Check

jobs:
  deploy:
    name: Deployment
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      # - name: Calculate depth
      #   id: depth
      #   run: |
      #     echo DEPTH=$(($(echo '${{toJSON(github.event.commits)}}' | jq '. | length') + 1))
      #     echo ::set-output name=DEPTH::$(($(echo '${{toJSON(github.event.commits)}}' | jq '. | length') + 1))
      - name: Checkout code
        uses: actions/checkout@v2
      #   with:
      #     fetch-depth: ${{steps.depth.outputs.DEPTH}}
      # - name: Check changes
      #   run: |
      #     git diff --name-only $(echo ${{github.event.compare}} | grep -oE '([a-z0-9]+\.\.\.[a-z0-9]+)')
      #     if ! git diff --name-only $(echo ${{github.event.compare}} | grep -oE '([a-z0-9]+\.\.\.[a-z0-9]+)') | grep -E '^((Dialog)|(Manual)|(Menu)|(Module)|(Other)|(StringTable)|(System)|(VersionInfo)|(240)\/)'; then
      #       echo "No files translated. Stopping!"
      #       exit 1
      #     else
      #       echo "Some files translated. Continuing."
      #     fi
      - name: Set enviroment variables
        run: |
          echo BUILD_DATE="$(date +%Y%m%d%H%M%S)"
          echo VERSION_NUM="$(cat version.txt)"
          echo ::set-env name=BUILD_DATE::"$(date +%Y%m%d%H%M%S)"
          echo ::set-env name=VERSION_NUM::"$(cat version.txt)"
      - name: Set version on executable
        run: |
          cd VersionInfo
          sed -i '2s/.*/FILEVERSION 1,43,${{env.VERSION_NUM}},0/' 1.rc
          sed -i '3s/.*/PRODUCTVERSION 1,43,${{env.VERSION_NUM}},0/' 1.rc
          sed -i '12s/.*/		VALUE "FileVersion", "1.43-${{env.VERSION_NUM}}-artifact.${{env.BUILD_DATE}}"/' 1.rc
          sed -i '17s/.*/		VALUE "ProductVersion", "1.43-${{env.VERSION_NUM}}-artifact.${{env.BUILD_DATE}}"/' 1.rc
      - name: Install required packages
        run: choco install reshack python3
      - name: Prepare _compile folder
        run: |
          rm -rf _compile
          mkdir _compile
          cp -r _deploy/Domino143/* _compile
      - name: Build (part 1, bash)
        run: |
          cd _compile
          echo "[FILENAMES] 
          Exe=  Domino.exe 
          SaveAs= Domino.exe 
          Log=  CON 
          [COMMANDS] 
          -delete  MENU,, 
          -delete  DIALOG,, 
          -delete  STRINGTABLE,, 
          -delete  VERSIONINFO,, 
          -delete  240,,
          -add   Menu.res, MENU,, 
          -add   Dialog.res, DIALOG,, 
          -add   StringTable.res, STRINGTABLE,,
          -add   VersionInfo.res, VERSIONINFO,,
          -add   240.res, 240,," > tmp.txt
          cat ../Dialog/* > Dialog.rc
          cat ../Menu/* > Menu.rc
          cat ../StringTable/* > StringTable.rc
          cat ../VersionInfo/* > VersionInfo.rc
          mkdir 240
          cp ../240/240.rc 240
          for file in ../240/*.bin.txt; do
            f="$(basename -s .txt $file)"
            python3 "../_deploy/parsecombo.py" pack $file 240/$f
          done
      - name: Build (part 2, cmd)
        shell: cmd
        run: |
          cd _compile
          "C:\Program Files (x86)\Resource Hacker\ResourceHacker.exe" -open Dialog.rc -save Dialog.res -action compile -log CON 
          "C:\Program Files (x86)\Resource Hacker\ResourceHacker.exe" -open Menu.rc -save Menu.res -action compile -log CON
          "C:\Program Files (x86)\Resource Hacker\ResourceHacker.exe" -open StringTable.rc -save StringTable.res -action compile -log CON
          "C:\Program Files (x86)\Resource Hacker\ResourceHacker.exe" -open VersionInfo.rc -save VersionInfo.res -action compile -log CON
          "C:\Program Files (x86)\Resource Hacker\ResourceHacker.exe" -open 240/240.rc -save 240.res -action compile -log CON
          "C:\Program Files (x86)\Resource Hacker\ResourceHacker.exe" -script tmp.txt
      - name: Build (part 3, bash)
        run: |
          cd _compile
          touch Domino.exe
          rm -rf Manual
          cp -r ../Manual .
          cp -r ../Module .
          cp -r ../System .
          cp -r ../Other/* .
          rm -rf *.rc
          rm -rf *.res
          rm -rf tmp.*
          rm -rf 240
      - name: Prepare deployment
        run: |
          cd _compile
          cp ../_deploy/readme-translation.txt readme-translation.txt
          sed -i '2s/.*/Build ${{env.VERSION_NUM}}-artifact.${{env.BUILD_DATE}} (1.43-${{env.VERSION_NUM}}-artifact.${{env.BUILD_DATE}})/' readme-translation.txt
          7z a ../Domino143_Translated.zip *
          mv -v Domino.exe ../Domino_Translated.exe
      - name: Upload artifact 1
        uses: actions/upload-artifact@v1
        with:
          name: Domino143_Translated_v${{env.VERSION_NUM}}-artifact.${{env.BUILD_DATE}}.zip
          path: Domino143_Translated.zip
      - name: Upload artifact 2
        uses: actions/upload-artifact@v1
        with:
          name: Domino_Translated_v${{env.VERSION_NUM}}-artifact.${{env.BUILD_DATE}}.exe
          path: Domino_Translated.exe