on: workflow_dispatch

name: Release Deployment

jobs:
  deploy:
    name: Deployment
    runs-on: windows-latest
    if: github.actor == github.event.repository.owner.login
    defaults:
      run:
        shell: bash
    steps:

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install required packages
        run: choco install reshack

      - name: Build
        id: build
        run: |
          cd _script
          bash workflow/build-all-release.sh

      - name: Write release body
        run: |
          echo "\
          ## Release Notes

          ----

          *Built on ${{steps.build.outputs.BUILD_DATE_FULL}}.*" >> release.txt
          
      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: en.${{steps.build.outputs.VERSION_NUM}}
          name: Build ${{steps.build.outputs.VERSION_NUM}} (Release)
          files: |
            _script/dist/Domino143_Translated.zip
            _script/dist/Domino143_Translated.exe
            _script/dist/Domino144_Translated.zip
            _script/dist/Domino144_Translated.exe
          body_path: release.txt
          draft: true